---
sudo: required

language: ruby

rvm:
  - ruby-2.5.1

services:
  - docker

env:
  global:
    - LANG: en_US.utf8
    - LC_ALL: en_US.utf8
    - DISTRIBUTION: centos
    - VERSION: 7
    - INIT: /usr/lib/systemd/systemd
    - RUN_OPTS: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - DOCKERHUB_USER: imokuri123
  matrix:
    - PROXY: true
      BUILD: all
      PUSH_DOCKERHUB: false
    - PROXY: true
      BUILD: default
      PUSH_DOCKERHUB: true
      IMAGE: imokuri-devp
    - PROXY: false
      BUILD: all
      PUSH_DOCKERHUB: false
    - PROXY: false
      BUILD: default
      PUSH_DOCKERHUB: true
      IMAGE: imokuri-dev
    - PROXY: false
      BUILD: minimal
      PUSH_DOCKERHUB: false

before_install:
  - docker pull ${DISTRIBUTION}:${VERSION}
  - docker pull wernight/squid

  - CONTAINER_ID=$(mktemp)
  - docker run --detach ${RUN_OPTS} ${DISTRIBUTION}:${VERSION} "${INIT}" > "${CONTAINER_ID}"

  - |
    if [ ${PROXY} == true ]; then
      SQUID_CONTAINER_ID=$(mktemp)
      docker run --detach -p 3128:3128 wernight/squid > "${SQUID_CONTAINER_ID}"
      squid_container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(cat "${SQUID_CONTAINER_ID}"))
      docker exec --tty "$(cat ${CONTAINER_ID})" sed -i "\$aproxy=http://${squid_container_ip}:3128" /etc/yum.conf
    fi

  - docker exec --tty "$(cat ${CONTAINER_ID})" yum install -y sudo

script:
  - |
    if [ ${PROXY} == true ]; then
      docker exec --tty "$(cat ${CONTAINER_ID})" env LANG=en_US.utf8 LC_ALL=en_US.utf8 BUILD=${BUILD} http_proxy=http://${squid_container_ip}:3128 bash -c "$(curl -fsSL https://git.io/imokuri)"
    else
      docker exec --tty "$(cat ${CONTAINER_ID})" env LANG=en_US.utf8 LC_ALL=en_US.utf8 BUILD=${BUILD} bash -c "$(curl -fsSL https://git.io/imokuri)"
    fi

  - docker stop "$(cat ${CONTAINER_ID})"
  - if [ ${PROXY} == true ]; then docker stop "$(cat ${SQUID_CONTAINER_ID})"; fi

after_success:
  - |
    if [ ${PUSH_DOCKERHUB} == true ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
      docker commit "$(cat ${CONTAINER_ID})" ${IMAGE}
      docker tag ${IMAGE} ${DOCKERHUB_USER}/${IMAGE}
      docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASS}
      docker push ${DOCKERHUB_USER}/${IMAGE}
      docker logout
    fi

notifications:
  email: false
