---
sudo: required

language: ruby

rvm:
  - ruby-2.5.1

services:
  - docker

env:
  global:
    - LANG: en_US.utf8
    - LC_ALL: en_US.utf8
    - RUN_OPTS: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - DOCKERHUB_USER: imokuri123
    - IMAGE: imokuri-dev
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
      INIT: /usr/lib/systemd/systemd
      PROXY: true
      PUSH_DOCKERHUB: false
    - DISTRIBUTION: centos
      VERSION: 7
      INIT: /usr/lib/systemd/systemd
      PROXY: false
      # PUSH_DOCKERHUB: true
      PUSH_DOCKERHUB: false
    - DISTRIBUTION: jrei/systemd-ubuntu
      VERSION: 18.04
      INIT: /lib/systemd/systemd
      PROXY: true
      PUSH_DOCKERHUB: false
    - DISTRIBUTION: jrei/systemd-ubuntu
      VERSION: 18.04
      INIT: /lib/systemd/systemd
      PROXY: false
      # PUSH_DOCKERHUB: true
      PUSH_DOCKERHUB: false

before_install:
  - docker pull ${DISTRIBUTION}:${VERSION}
  - docker pull wernight/squid

  - CONTAINER_ID=$(mktemp)
  - docker run --detach ${RUN_OPTS} ${DISTRIBUTION}:${VERSION} "${INIT}" > "${CONTAINER_ID}"

  - |
    if [ ${PROXY} == true ]; then
      SQUID_CONTAINER_ID=$(mktemp)
      docker run --detach -p 3128:3128 wernight/squid > "${SQUID_CONTAINER_ID}"
      squid_container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(cat "${SQUID_CONTAINER_ID}"))
      if [ ${DISTRIBUTION} == "centos" ]; then
        docker exec --tty "$(cat ${CONTAINER_ID})" sed -i "\$aproxy=http://${squid_container_ip}:3128" /etc/yum.conf
      else
        docker exec --tty "$(cat ${CONTAINER_ID})" echo "Acquire::http::proxy \"http://${squid_container_ip}:3128/\";" > /etc/apt/apt.conf.d/00proxy
        docker exec --tty "$(cat ${CONTAINER_ID})" echo "Acquire::https::proxy \"http://${squid_container_ip}:3128/\";" >> /etc/apt/apt.conf.d/00proxy
      fi
    fi

  - |
    if [ ${DISTRIBUTION} == "centos" ]; then
      docker exec --tty "$(cat ${CONTAINER_ID})" yum install -y sudo
    else
      docker exec --tty "$(cat ${CONTAINER_ID})" apt update
      docker exec --tty "$(cat ${CONTAINER_ID})" apt install -y sudo
    fi

script:
  - |
    if [ ${PROXY} == true ]; then
      docker exec --tty "$(cat ${CONTAINER_ID})" env LANG=en_US.utf8 LC_ALL=en_US.utf8 http_proxy=http://${squid_container_ip}:3128 bash -c "$(curl -fsSL https://git.io/imokuri)"
    else
      docker exec --tty "$(cat ${CONTAINER_ID})" env LANG=en_US.utf8 LC_ALL=en_US.utf8 bash -c "$(curl -fsSL https://git.io/imokuri)"
    fi

  - docker stop "$(cat ${CONTAINER_ID})"
  - if [ ${PROXY} == true ]; then docker stop "$(cat ${SQUID_CONTAINER_ID})"; fi

# after_success:
#   - |
#     if [ ${PUSH_DOCKERHUB} == true ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
#       docker commit "$(cat ${CONTAINER_ID})" ${IMAGE}:${DISTRIBUTION}-${VERSION}
#       docker tag ${IMAGE} ${DOCKERHUB_USER}/${IMAGE}
#       docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASS}
#       docker push ${DOCKERHUB_USER}/${IMAGE}:${DISTRIBUTION}-${VERSION}
#       docker logout
#     fi

notifications:
  email: false
