sudo: required

services:
  - docker

env:
  matrix:
    - OS_DIST=centos
      OS_VERSION=7

before_install:
  - docker pull ${OS_DIST}:${OS_VERSION}

script:
  - docker run -i -t --rm=true ${OS_DIST}:${OS_VERSION} bash -c "yum install -y sudo; \
                                                                 $(curl -fsSL https://git.io/imokuri)"
