# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
ghc-options:
  "*": -Wall
templates:
  scm-init: git
  params:
    author-name: IMOKURI
    author-email: nenegi.01mo@gmail.com
    copyright: 2016 IMOKURI
    github-username: IMOKURI
    category: Development
