#!/usr/bin/env bash

set -e

##### Variables ###############################################################

export PATH=${HOME}/.local/bin:${HOME}/bin:${HOME}/.local/share/mise/shims:/usr/local/bin:${PATH}

# Defind Colors
BANNER="\033[38;2;101;178;255m" # BLUE
CLEAR_COLOR="\033[0m"

# Define path
DOTPATH="$HOME/.dotfiles"

##### Functions ###############################################################

COL=120

function _banner() {
    sep=$(for ((i = 1; i < COL; i++)); do echo -n =; done)
    printf "\n${BANNER}%s %s${CLEAR_COLOR}\n\n" "${1}" "${sep:${#1}}"
}

##### Download Dotfiles ######################################################

_banner "Download Dotfiles..."

if [[ ! -d "${DOTPATH}" ]]; then
    git clone --recursive https://github.com/IMOKURI/dotfiles.git "${DOTPATH}"
fi

##### Setup dotfiles #########################################################

_banner "Setup dotfiles..."

pushd "$(pwd)"
cd "${DOTPATH}"
make install
popd

##### Instruct next steps #####################################################

_banner "Well done! Please restart your shell session to apply the changes."
