#!/usr/bin/env bash

set -e

##### Variables ###############################################################

# Defind Colors
#RED="\033[38;2;255;84;88m"
#GREEN="\033[38;2;98;209;150m"
#YELLOW="\033[38;2;255;179;120m"
BLUE="\033[38;2;101;178;255m"
#MAGENTA="\033[38;2;144;108;255m"
#CYAN="\033[38;2;99;242;241m"
CLEAR_COLOR="\033[0m"

INFO="GREEN"
#WARN="YELLOW"
#ERROR="RED"

# Define path
DOTPATH="$HOME/.dotfiles"
NEOVIMPATH="$HOME/src/neovim"
GITPATH="$HOME/src/git"

##### Functions ###############################################################

function _banner(){
  sep=$(for ((i=1; i<$(tput cols); i++)); do echo -n =; done)
  printf "\n${BLUE}%s %s${CLEAR_COLOR}\n\n" "${1}" "${sep:${#1}}"
}

function _logger(){
  COLOR="${1}"
  printf "${!COLOR}%s${CLEAR_COLOR}\n" "${2}"
}

##### Set Proxy ###############################################################

_banner "Set Proxy if Available..."

if [[ "${http_proxy}" ]]; then
  if ! grep -q proxy /etc/yum.conf; then
    echo "proxy=${http_proxy}" >> /etc/yum.conf
  fi
fi

##### Setup repositories ######################################################

_banner "Setup repositories..."

if [[ ! -f /etc/yum.repos.d/ius.repo ]]; then
  _logger "${INFO}" "Install IUS repository"
  curl -fsSL https://raw.githubusercontent.com/iuscommunity/automation-examples/bash/enable-ius.sh | sudo -E bash
fi

if [[ ! -f /etc/yum.repos.d/github_git-lfs.repo ]]; then
  _logger "${INFO}" "Install Git LFS repository"
  curl -fsSL https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | sudo -E bash
fi

if [[ ! -f /etc/yum.repos.d/nodesource-el.repo ]]; then
  _logger "${INFO}" "Install Nodejs repository"
  curl -fsSL https://rpm.nodesource.com/setup_11.x | sudo -E bash
fi

if [[ ! -f /etc/yum.repos.d/carlwgeorge-ripgrep-epel-7.repo ]]; then
  _logger "${INFO}" "Install Ripgrep repository"
  sudo -E yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo
fi

##### Install packages ########################################################

_banner "Install Packages..."

sudo -E yum install -y autoconf automake cmake expat-devel gcc gcc-c++ git libcurl-devel libffi-devel libtool make ninja-build nodejs openssl-devel patch pkgconfig python python-devel python36u python36u-devel ripgrep unzip which

##### Clone Dotfiles ##########################################################

_banner "Clone Dotfiles..."

if [[ ! -d "${DOTPATH}" ]]; then
  _logger "${INFO}" "Clone dotfiles repository"
  git clone --recursive https://github.com/IMOKURI/dotfiles.git "${DOTPATH}"
else
  _logger "${INFO}" "Update dotfiles repository"
  pushd "$(pwd)"
  cd "${DOTPATH}"
  git pull
  git submodule init
  git submodule update
  git submodule foreach git pull origin master
  popd
fi

##### Clone git ###############################################################

_banner "Clone Git..."

if [[ ! -d "${GITPATH}" ]]; then
  _logger "${INFO}" "Clone git"
  git clone https://github.com/git/git.git "${GITPATH}"
  sudo -E yum remove -y git
else
  _logger "${INFO}" "Update git repository"
  pushd "$(pwd)"
  cd "${DOTPATH}"
  make update-git
  popd
fi

##### Install git #############################################################

_banner "Install Git..."

pushd "$(pwd)"
cd "${DOTPATH}"
make build-git
popd

_logger "${INFO}" "Install Git-LFS"

export PATH="$HOME/bin:$PATH"
sudo -E yum install -y git-lfs

##### Download git scripts ####################################################

_banner "Download Git Scripts..."

mkdir -p "$HOME/.local/bin"

curl -o "$HOME/.local/bin/git-completion.bash" https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

curl -o "$HOME/.local/bin/git-prompt.sh" https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

##### Install python packages #################################################

_banner "Install Pip..."

command -v pip3.6 &> /dev/null || curl -fsSL "https://bootstrap.pypa.io/get-pip.py" | sudo -E python3.6

_banner "Install Python Packages..."

sudo -E pip install ansible pipenv pipenv-pipes

##### Install nodejs packages #################################################

_banner "Install NodeJS Packages..."

sudo -E npm -g install doctoc neovim jsonlint remark-cli

##### Clone neovim ############################################################

_banner "Clone Neovim..."

if [[ ! -d "${NEOVIMPATH}" ]]; then
  _logger "${INFO}" "Clone neovim"
  git clone https://github.com/neovim/neovim.git "${NEOVIMPATH}"
else
  _logger "${INFO}" "Update neovim repository"
  pushd "$(pwd)"
  cd "${DOTPATH}"
  make update-neovim
  popd
fi

##### Install neovim ##########################################################

_banner "Install Neovim..."

pushd "$(pwd)"
cd "${DOTPATH}"
make build-neovim
popd

##### Install dotfiles ########################################################

_banner "Install dotfiles..."

pushd "$(pwd)"
cd "${DOTPATH}"
make install
echo -e "\nif [ -f ~/.config/bashrc ]; then\n  . ~/.config/bashrc\nfi" >> "${HOME}/.bashrc"
echo -e "\nif [ -f ~/.config/profile.d/local.sh ]; then\n  . ~/.config/profile.d/local.sh\nfi" >> "${HOME}/.bash_profile"
popd

_banner "Finished!"
