---
- hosts: localhost
  tasks:
      - name: Get IUS Repository Installer
        uri:
            url: https://setup.ius.io
            return_content: true
        register: ius

      - name: Install IUS Repository
        shell: "bash -c '{{ ius.content }}'"

      - name: Get Haskell Stack Installer
        uri:
            url: https://get.haskellstack.org
            return_content: true
        register: stack

      - name: Install Haskell Stack
        shell: "bash -c '{{ stack.content }}'"

      - name: Install Python2 Packages
        pip:
            name: "{{ item }}"
        with_items:
            - neovim
            - jedi
            - flake8
            - icdiff
            - Pygments
            - virrualenvwrapper

      - name: Install Packages
        yum:
            name: "{{ item }}"
        with_items:
            - git2u
            - python36u
            - python36u-pip
            - neovim

      - name: Create Symbolic Links
        file:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
        with_items:
            - { src: '/usr/bin/python3.6', dest: '/usr/bin/python3' }
            - { src: '/usr/bin/pip3.6', dest: '/usr/bin/pip3' }

      - name: Set Alternative Commands
        alternatives:
            name: "{{ item.name }}"
            link: "{{ item.link }}"
            path: "{{ item.path }}"
            priority: "{{ item.priority }}"
        with_items:
            - { name: 'python', link: '/usr/local/bin/python', path: '/usr/bin/python2', priority: 20 }
            - { name: 'python', link: '/usr/local/bin/python', path: '/usr/bin/python3', priority: 30 }
            - { name: 'pip', link: '/usr/local/bin/pip', path: '/usr/bin/pip2', priority: 20 }
            - { name: 'pip', link: '/usr/local/bin/pip', path: '/usr/bin/pip3', priority: 30 }
            - { name: 'vi', link: '/usr/local/bin/vi', path: "{{ lookup('pipe', 'which nvim') }}", priority: 100 }

      - name: Install Python3 Packages
        pip:
            name: "{{ item }}"
        with_items:
            - neovim
            - jedi
            - flake8
            - icdiff
            - Pygments
            - virrualenvwrapper

      - name: Create Config Directory
        file:
            path: ~/.config
            state: directory

      - name: Clone Dotfiles Repository
        git:
            repo: https://github.com/IMOKURI/dotfiles.git
            dest: ~/.dotfiles

      - name: Create Symbolic Links To Dotfiles
        make:
            chdir: ~/.dotfiles
            target: deploy

      - name: Setup Virtualenv Dir
        shell: source /usr/bin/virtualenvwrapper.sh
        environment:
            WORKON_HOME: ~/.virtualenvs

      - name: Setup Virtualenv Default Package Dir
        file:
            path: "{{ item }}"
            state: directory
        with_items:
            - ~/.virtualenvs/deps
            - ~/.virtualenvs/deps3

      - name: Install Virtualenv Default Package for Python2
        shell: pip2 install -U --target ~/.virtualenvs/deps neovim jedi flake8

      - name: Install Virtualenv Default Package for Python3
        shell: pip3 install -U --target ~/.virtualenvs/deps3 neovim jedi flake8

      - name: Setup Virtualenv Boot Script
        shell: |
            sed 's/^ //' << EOS | cat >> ~/.virtualenvs/postmkvirtualenv
            # find directory
            SITEDIR=\$(virtualenvwrapper_get_site_packages_dir)
            PYVER=\$(virtualenvwrapper_get_python_version)

            # create new .pth file with our path depending of python version
            if [[ \$PYVER == 3* ]];
            then
                echo "\$HOME/.virtualenvs/deps3/" > "\$SITEDIR/extra.pth";
            else
                echo "\$HOME/.virtualenvs/deps/" > "\$SITEDIR/extra.pth";
            fi
            EOS
