[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'neomake/neomake'
hook_source = '''
  let g:neomake_open_list = 2
  let g:neomake_error_sign = {'text': 'E>', 'texthl': 'NeomakeErrorSign'}
  let g:neomake_warning_sign = {'text': 'W>', 'texthl': 'NeomakeWarningSign',}
  let g:neomake_info_sign = {'text': 'I>', 'texthl': 'NeomakeInfoSign'}
'''
hook_add = '''
  autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'sedan07/vim-mib'
on_ft = 'mib'
