[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'challenger-deep-theme/vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_guide_size = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_auto_colors = 0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#212121 ctermbg=0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#101010 ctermbg=8
'''

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
  nmap <Leader>m <Plug>(quickhl-manual-this)
  xmap <Leader>m <Plug>(quickhl-manual-this)
  nmap <Leader>M :<C-u>QuickhlManualReset<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <silent> <Leader>s :<C-u>Gstatus<CR>
  nnoremap <silent> <Leader>d :<C-u>Gdiff<CR>
'''

[[plugins]]
repo = 'tpope/vim-sleuth'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['vim-misc']
hook_add = '''
  let s:local_session_directory = xolox#misc#path#merge(getcwd(), '.vimsessions')
  if isdirectory(s:local_session_directory)
    let g:session_directory = s:local_session_directory
    let g:session_autosave = 'yes'
    let g:session_autoload = 'yes'
    let g:session_autosave_periodic = 1
  else
    let g:session_autosave = 'no'
    let g:session_autoload = 'no'
  endif
  unlet s:local_session_directory
'''
