[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'challenger-deep-theme/vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_guide_size = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_auto_colors = 0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#212121 ctermbg=0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#424242 ctermbg=8
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nmap <Leader>g [figitive]
  nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
  nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
  nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
  nnoremap <silent> [figitive]l :<C-u>Glog<CR>
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
hook_post_update = '''
  if g:env =~# 'WINDOWS'
    let cmd = 'powershell .\\install.ps1'
  else
    let cmd = 'bash install.sh'
  endif
  let g:dein#plugin.build = cmd
'''
hook_add = '''
  set hidden
  let g:LanguageClient_autoStart = 1
  let g:LanguageClient_selectionUI = 'location-list'

  let g:LanguageClient_serverCommands = {}
  if executable('pyls')
    let g:LanguageClient_serverCommands['python'] = ['pyls']
  endif
  if executable('bash-language-server')
    let g:LanguageClient_serverCommands['sh'] = ['bash-language-server', 'start']
  endif

  let g:LanguageClient_settingsPath = expand('~/.config/nvim/settings.json')

  function SetLSPShortcuts()
    nnoremap <leader>ld :call LanguageClient#textDocument_definition()<CR>
    nnoremap <leader>lr :call LanguageClient#textDocument_rename()<CR>
    nnoremap <leader>lf :call LanguageClient#textDocument_formatting()<CR>
    nnoremap <leader>lt :call LanguageClient#textDocument_typeDefinition()<CR>
    nnoremap <leader>lx :call LanguageClient#textDocument_references()<CR>
    nnoremap <leader>la :call LanguageClient_workspace_applyEdit()<CR>
    nnoremap <leader>lc :call LanguageClient#textDocument_completion()<CR>
    nnoremap <leader>lh :call LanguageClient#textDocument_hover()<CR>
    nnoremap <leader>ls :call LanguageClient_textDocument_documentSymbol()<CR>
    nnoremap <leader>lm :call LanguageClient_contextMenu()<CR>
  endfunction()

  augroup LSP
    autocmd!
    autocmd FileType python,sh call SetLSPShortcuts()
  augroup END
'''

[[plugins]]
repo = 'tpope/vim-sleuth'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['vim-misc']
hook_add = '''
  let s:local_session_directory = xolox#misc#path#merge(getcwd(), '.vimsessions')
  if isdirectory(s:local_session_directory)
    let g:session_directory = s:local_session_directory
    let g:session_autosave = 'yes'
    let g:session_autoload = 'yes'
    let g:session_autosave_periodic = 1
  else
    let g:session_autosave = 'no'
    let g:session_autoload = 'no'
  endif
  unlet s:local_session_directory
'''
