---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    gather_facts: false
    foo: bar
  children:
    groupA:
      children:
        groupA1:
          vars:
            hoge:
              - fuga
          hosts:
            hostA:
              imo: kuri
