[hostname]
style = "bold green"

[character]
success_symbol = '[](bold green) '
error_symbol = '[](bold red) '
# format = "$symbol"

[directory]
truncation_length = 5
truncation_symbol = ".../"
read_only = " "

[git_branch]
symbol = "  "

[git_status]
conflicted = " "
deleted = " "
renamed = ""
modified = ""
untracked = ""
staged = " "
stashed = ""
ahead = ""
behind = ""
diverged = ""
# up_to_date = " "

[sudo]
disabled = false

[kubernetes]
disabled = false
symbol = "☸  "

[kubernetes.context_aliases]
".*/(?P<cluster>[\\w-]+).*/.*" = "$cluster"

[gcloud]
disabled = true
