[hostname]
style = "bold green"

[memory_usage]
disabled = false
threshold = -1
symbol = " "
format = 'via $symbol [${ram}]($style) '

[directory]
truncation_length = 5
truncation_symbol = ".../"
read_only = " "

[git_branch]
symbol = "  "

[git_status]
conflicted = " "
deleted = " "
renamed = " "
modified = " "
untracked = " "
staged = " "
stashed = " "
ahead = " "
behind = " "
diverged = "  "
up_to_date = " "

[sudo]
disabled = false
symbol = " "

[python]
symbol = " "

[kubernetes]
disabled = false

[kubernetes.context_aliases]
".*/(?P<cluster>[\\w-]+).*/.*" = "$cluster"

[gcloud]
disabled = true
