[hostname]
style = "bold green"

[directory]
truncation_length = 5
truncation_symbol = ".../"

[git_branch]
symbol = "  "

[git_status]
conflicted = " "
deleted = " "
renamed = " "
modified = " "
untracked = " "
staged = " "
stashed = " "
ahead = " "
behind = " "
diverged = "  "
up_to_date = " "

[kubernetes]
disabled = false

[kubernetes.context_aliases]
".*/(?P<cluster>[\\w-]+).*/.*" = "$cluster"

[gcloud]
disabled = true
