name: E2E Test

on:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '26 9 * * 1'

jobs:
  ubuntu:
    strategy:
      fail-fast: true
      matrix:
        os_name:
          - ubuntu
        os_version:
          - 24.04
          - 26.04

    runs-on: ubuntu-latest
    container: ${{ matrix.os_name }}:${{ matrix.os_version }}

    steps:
    - name: Install requirements
      run: |
        apt-get update
        apt-get install -y curl

    - uses: actions/checkout@v6

    - name: Install dotfiles from branch
      env:
        LANG: en_US.utf8
        HOME: /root
        MISE_GITHUB_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}
      run: |
        cp -a "${GITHUB_WORKSPACE}/.config/mise/config.toml" /root/.mise-config.toml
        bash ${GITHUB_WORKSPACE}/install
