# This is a basic workflow to help you get started with Actions

name: E2E Test

on:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '26 9 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    strategy:
      fail-fast: true
      matrix:
        os_version:
          - 20.04

    runs-on: ubuntu-latest
    container: jrei/systemd-ubuntu:${{ matrix.os_version }}

    steps:
    - name: Install requirements
      run: |
        apt update
        apt install -y curl sudo

    - name: Install dotfiles
      run: |
        env LANG=en_US.utf8 HOME=/root bash -c "$(curl -fsSL https://git.io/imokuri)"

  ubuntu_proxy:
    strategy:
      fail-fast: true
      matrix:
        os_version:
          - 20.04

    runs-on: ubuntu-latest
    container: jrei/systemd-ubuntu:${{ matrix.os_version }}

    services:
      squid:
        image: wernight/squid
        ports:
          - 3128:3128

    steps:
    - name: Install requirements
      run: |
        env http_proxy=http://squid:3128 apt update
        env http_proxy=http://squid:3128 apt install -y curl sudo

    - name: Install dotfiles
      run: |
        env http_proxy=http://squid:3128 LANG=en_US.utf8 HOME=/root bash -c "$(curl -fsSL https://git.io/imokuri)"
        cat /root/.config/git/config.proxy

  centos:
    strategy:
      fail-fast: true
      matrix:
        os_version:
          - 8

    runs-on: ubuntu-latest
    container: centos:${{ matrix.os_version }}

    steps:
    - name: Install requirements
      run: |
        yum install -y sudo

    - name: Install dotfiles
      run: |
        env LANG=en_US.utf8 HOME=/root bash -c "$(curl -fsSL https://git.io/imokuri)"

  centos_proxy:
    strategy:
      fail-fast: true
      matrix:
        os_version:
          - 8

    runs-on: ubuntu-latest
    container: centos:${{ matrix.os_version }}

    services:
      squid:
        image: wernight/squid
        ports:
          - 3128:3128

    steps:
    - name: Install requirements
      run: |
        sed -i "\$aproxy=http://squid:3128" /etc/yum.conf
        yum install -y sudo

    - name: Install dotfiles
      run: |
        env http_proxy=http://squid:3128 LANG=en_US.utf8 HOME=/root bash -c "$(curl -fsSL https://git.io/imokuri)"
        cat /root/.config/git/config.proxy
