# This is a basic workflow to help you get started with Actions

name: E2E Test

on:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '26 9 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    strategy:
      fail-fast: true
      matrix:
        os_name:
          - ubuntu
        os_version:
          - 22.04
          - 24.04

    runs-on: ubuntu-latest
    container: ${{ matrix.os_name }}:${{ matrix.os_version }}

    steps:
    - name: Install requirements
      run: |
        apt-get update
        apt-get install -y curl sudo

    - name: Install dotfiles
      run: |
        env LANG=en_US.utf8 HOME=/root bash -c "$(curl -fsSL https://git.io/imokuri)"

  ubuntu_proxy:
    strategy:
      fail-fast: true
      matrix:
        os_name:
          - ubuntu
        os_version:
          - 22.04
          - 24.04

    runs-on: ubuntu-latest
    container: ${{ matrix.os_name }}:${{ matrix.os_version }}

    services:
      squid:
        image: wernight/squid
        ports:
          - 3128:3128

    steps:
    - name: Install requirements
      run: |
        env https_proxy=http://squid:3128 http_proxy=http://squid:3128 apt-get update
        env https_proxy=http://squid:3128 http_proxy=http://squid:3128 apt-get install -y curl sudo

    - name: Install dotfiles
      run: |
        env https_proxy=http://squid:3128 http_proxy=http://squid:3128 LANG=en_US.utf8 HOME=/root bash -c "$(curl -fsSL https://git.io/imokuri)"
        cat /root/.config/git/config.proxy

  ubuntu_dont_sudo:
    strategy:
      fail-fast: true
      matrix:
        os_name:
          - ubuntu
        os_version:
          - 22.04
          - 24.04

    runs-on: ubuntu-latest
    container: ${{ matrix.os_name }}:${{ matrix.os_version }}

    steps:
    - name: Install requirements
      run: |
        apt-get update
        apt-get install -y curl git

    - name: Install dotfiles
      run: |
        env LANG=en_US.utf8 HOME=/root DONT_SUDO=true bash -c "$(curl -fsSL https://git.io/imokuri)"
