[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'challenger-deep-theme/vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
    let g:rooter_change_directory_for_non_project_files = 'current'
    let g:rooter_patterns = ['.git', '.git/']
'''

