[[plugins]]
repo = 't9md/vim-quickhl'
on_map = '<Plug>(quickhl-'
hook_add = '''
    nmap <silent> <Leader>m <Plug>(quickhl-manual-this)
    xmap <silent> <Leader>m <Plug>(quickhl-manual-this)
    nmap <silent> <Leader>M <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = ['toml', 'markdown']

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['toml', 'markdown']

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['yaml', 'jinja2']
hook_add = '''
  let g:ansible_unindent_after_newline = 1
  let g:ansible_extra_keywords_highlight = 1
  let g:ansible_template_syntaxes = {'*.py.j2': 'python', '*.cfg.j2': 'cfg', '*.yaml.j2': 'yaml', '*.yml.j2': 'yaml'}
'''

[[plugins]]
repo = 'martinda/Jenkinsfile-vim-syntax'
on_ft = 'Jenkinsfile'

[[plugins]]
repo = 'LeafCage/yankround.vim'
on_map = '<Plug>(yankround-'
hook_add = '''
    let g:yankround_dir = $XDG_DATA_HOME . '/yankround'
    let g:yankround_use_region_hl = 1

    nmap p <Plug>(yankround-p)
    xmap p <Plug>(yankround-p)
    nmap P <Plug>(yankround-P)
    nmap <C-p> <Plug>(yankround-prev)
    nmap <C-n> <Plug>(yankround-next)
'''

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'
on_cmd = ['VimHelpGenerator', 'VimHelpGeneratorVirtual']
hook_add = '''
    let g:vimhelpgenerator_defaultlanguage = 'en'
    let g:vimhelpgenerator_gitignore_lines = []
'''
