[[plugins]]
repo = 'haya14busa/is.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
depends = 'is.vim'
hook_add = '''
    nmap n <Plug>(is-nohl)<Plug>(anzu-n)
    nmap N <Plug>(is-nohl)<Plug>(anzu-N)
    nmap * <Plug>(anzu-star)<Plug>(is-nohl-1)

    augroup Anzu
        autocmd!
        autocmd WinLeave,TabLeave * call anzu#clear_search_status()
    augroup END
'''

[[plugins]]
repo = 'tpope/vim-commentary'

# vim:set foldmethod=marker:
