[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['yaml', 'jinja2']
hook_add = '''
  let g:ansible_unindent_after_newline = 1
  let g:ansible_extra_keywords_highlight = 1
  let g:ansible_template_syntaxes = {'*.yaml.j2': 'yaml', '*.yml.j2': 'yaml'}
'''

[[plugins]]
repo = 'martinda/Jenkinsfile-vim-syntax'
on_ft = 'Jenkinsfile'
